//User and auto-imports pre-defined
import java.util.*;
import javax.swing.*;
import javax.swing.event.*;
import java.awt.*;
import java.awt.event.*;
import java.io.*;
//Autogenerated class
public class Main {
public static void main(String[] args) {
JFrame frame = new JFrame();
frame.setSize(640, 480);
frame.setVisible(true);
}
}