//User and auto-imports pre-defined
import javax.swing.*;
import javax.swing.event.*;
import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.util.ArrayList;
//Autogenerated class
public class Main {
public static void main(String[] args) {
System.out.println("I WANT TO BREAK YOU");



ArrayList<String> test = new ArrayList<String>();


test.add("Hey");

for (String str: test)
{
        System.out.println(str);
}


}
}